fix issue #499
sap-linuxlab/community.sap_install pull request #537
Opened 2023-11-24 14:12 UTC by itdose2023

here is our suggestion to use sapconf for SLES as an alternative to saptune which is only available for SLES for SAP applications

2023-11-25 10:43 UTC, rhmk commented on roles/sap_netweaver_preconfigure/defaults/main.yml
What is the reason, that sap_netweaver_preconfigure_min_swap_space_mb is changed. Is that a leftover from previous changes in dev? Need to check with current dev tree and figure out where `__sap_netweaver_preconfigure_min_swap_space_mb` is defined

2023-11-25 10:44 UTC, rhmk commented on roles/sap_netweaver_preconfigure/defaults/main.yml
Maybe the same is true for the other single quotes that are removed. We need to have a closer look to this.

2023-11-25 10:46 UTC, rhmk reviewed
In general the changes look good to me. See my comments w/rt defaukts/main.yml. Somebody need to double check, but if that is ok or fixed, I am fine with a merge.

2023-11-27 09:15 UTC, marcelmamula commented on roles/sap_hana_preconfigure/defaults/main.yml
I don't  think this should be user input. Default value should be true and false for pure SLES should be decided using logic following SUSE KBA: https://www.suse.com/support/kb/doc/?id=000019341

  tasks:
      - name: Get contents of /etc/products.d/baseproduct
        ansible.builtin.stat:
          path: /etc/products.d/baseproduct
        register: sles_baseproduct
        when: ansible_os_family == 'Suse'

      - name: Setfact if baseproduct contains SLES without SLES_SAP
        ansible.builtin.set_fact:
          __sap_hana_preconfigure_run_saptune: false
        when: 
          - '"SLES_SAP" not in sles_baseproduct.stat.lnk_target'
          - '"SLES" in sles_baseproduct.stat.lnk_target'
          - ansible_os_family == 'Suse'

2023-11-27 09:29 UTC, marcelmamula commented
I think redundant when conditionals should be replaced by blocks with single when condition to remove clutter - where possible of course.

2023-11-27 09:45 UTC, rhmk commented on roles/sap_hana_preconfigure/vars/main.yml
RHEL does not use saptune. ou can savely remove that comment

2023-11-28 08:05 UTC, itdose2023 commented on roles/sap_hana_preconfigure/defaults/main.yml
Hi,
We are new here - do you mean, that we should add your proposal above to the code via a new issue&Merge request or will you add this statements?
regards, Bruno & Wolfgang

2023-11-28 11:13 UTC, marcelmamula commented on roles/sap_hana_preconfigure/defaults/main.yml
Hello Bruno, Wolfgang,
Please add this to your code to remove need for user input so it automatically adjusts based on baseproduct value on SLES. This PR will most likely not get approved to be merged in current state without changes mentioned in comments.

Same goes with my other comment to simplify code by using blocks with when condition instead of using each task with same condition.

2023-11-30 13:41 UTC, itdose2023 commented
Hi,
we updated the roles to the proposals from M.mamula:
1.) created block to remove clutter with many when conditions for saptune
2.) Automatic detection for SLES for SAP Application to decide between sapconf / saptune
regards,
Bruno & Wolfgang

2023-11-30 23:07 UTC, sean-freeman requested changes

2023-12-04 07:53 UTC, itdose2023 commented on roles/sap_netweaver_preconfigure/defaults/main.yml
> +sap_preconfigure_run_saptune: "{{ __sap_netweaver_preconfigure_run_saptune }}"
added new line to the end of the file

2023-12-04 08:02 UTC, itdose2023 commented on roles/sap_hana_preconfigure/defaults/main.yml
> +# 15Nov2023 itbehsw - introduced saptune/sapconf decision
removed: Date stamp and username

2023-12-04 08:56 UTC, itdose2023 commented on roles/sap_hana_preconfigure/tasks/SLES/installation.yml
> +    not __sap_hana_preconfigure_run_saptune
new line added.

2023-12-04 08:57 UTC, itdose2023 commented on roles/sap_hana_preconfigure/tasks/SLES/configuration.yml
> +  when:
done.

2023-12-04 15:27 UTC, sean-freeman commented on roles/sap_netweaver_preconfigure/tasks/SLES/configuration.yml
> +# 12Nov2023_itdose2023: Add when Statement
I am OK with keeping them outside, as explained the when clause contains different AND conditions

2024-01-13 15:13 UTC, merged

2024-01-13 15:13 UTC, sean-freeman commented
This should not have been delayed during the holiday season, approving and merging - then will fix linting issues in a new PR