sap_vm_preconfigure: implemented ansible-lint changes
sap-linuxlab/community.sap_install pull request #554
Opened 2023-12-19 17:29 UTC by newkit

Implemented the ansible-lint suggestions.

There are three open issues in code you have added @sean-freeman, could you please take a look?

```
yaml[indentation]: Wrong indentation: expected 4 but found 2
tasks/detect_platform/main.yml:82

yaml[indentation]: Wrong indentation: expected 4 but found 2
tasks/detect_platform/main.yml:115

yaml[empty-lines]: Too many blank lines (1 > 0)
tasks/detect_platform/main.yml:131
```

2024-01-12 14:46 UTC, sean-freeman requested changes
After typo fix, lgtm 👍

2024-01-12 14:46 UTC, sean-freeman commented on roles/sap_vm_preconfigure/tasks/platform/hyp_redhat_rhel_kvm_vm/assert-set-tuned-profile.yml
> +      iansible.builtin.assert:
Typo

2024-01-12 16:51 UTC, berndfinger commented
@newkit Please remove the changes for file `roles/sap_vm_preconfigure/.ansible-lint` from this PR in a new commit. The file has already been updated in the meantime with additional changes in the already merged PR https://github.com/sap-linuxlab/community.sap_install/pull/594.

2024-01-15 15:17 UTC, berndfinger reviewed
LGTM

2024-01-15 15:34 UTC, berndfinger approved these changes
LGTM

2024-01-15 16:07 UTC, sean-freeman approved these changes
lgtm 👍

2024-01-15 16:12 UTC, merged