sap_hypervisor_node_preconfigure: Security fixes regarding assert|that
sap-linuxlab/community.sap_install pull request #586
Opened 2024-01-11 13:38 UTC by newkit

Adressed fixes required due to issues with assert | that statements when using curled brackets. 
Tested the role and fixed minor issues as well.

2024-01-11 14:05 UTC, Wabri requested changes
2 minimal necessary changes in order to pass the ansible-lint workflow

2024-01-11 14:05 UTC, Wabri commented on roles/sap_hypervisor_node_preconfigure/tasks/platform/redhat_rhel_kvm/assert-configuration.yml
> +      ansible.builtin.set_fact:
```suggestion
      ansible.builtin.set_fact:
```

2024-01-11 14:05 UTC, Wabri commented on roles/sap_hypervisor_node_preconfigure/tasks/platform/redhat_rhel_kvm/assert-configuration.yml
> +        that: sap_hypervisor_node_preconfigure_register_assert_nx_huge_pages == sap_hypervisor_node_preconfigure_kvm_nx_huge_pages
```suggestion
        that: sap_hypervisor_node_preconfigure_register_assert_nx_huge_pages == sap_hypervisor_node_preconfigure_kvm_nx_huge_pages
```

2024-01-11 15:09 UTC, newkit commented
Thanks @Wabri, I've made the two changes requested. Was pushing a bit too fast before checking for the lint results *ducks*

2024-01-11 15:15 UTC, Wabri commented
Awesome ⚡

2024-01-11 15:46 UTC, newkit reviewed
Addressed commented issues about trailing spaces.

2024-01-15 16:18 UTC, berndfinger reviewed
LGTM

2024-01-15 16:29 UTC, sean-freeman approved these changes
lgtm 👍

2024-01-15 16:30 UTC, berndfinger approved these changes

2024-01-15 16:31 UTC, sean-freeman commented
@Wabri please confirm you are happy your changes have been met by providing `Approve` and `lgtm :+1:` when ready

2024-01-15 17:06 UTC, newkit commented
Confirm Wabri's review and requested changes have been met, this PR is ready to merge

2024-01-15 17:34 UTC, sean-freeman commented
OK I can see @Wabri confirmed above. Will merge given the changes requested were trailing spaces.

2024-01-15 17:34 UTC, merged