sap_hana_install: Add support for fapolicyd
sap-linuxlab/community.sap_install pull request #727
Opened 2024-04-26 13:12 UTC by berndfinger

This PR adds support for fapolicyd:
- The presence of the package `fapolicyd` is ensured.
- The integrity setting in `/etc/fapolicyd/fapolicyd.conf` will be `sha256` instead of the default `none`.
- The presence of a new fapolicyd rule file in `/etc/faplicyd/rules.d`, for protecting shell scripts, will be ensured. 
- The presence of all executables under `/hana` and `/usr/sap` in fapolicyd trust files in `/etc/faplicyd/trust.d` will be ensured.
- The service `fapolicyd` is enabled and running.

I introduced a new role parameter, `sap_hana_install_root_path` which is needed for this functionality, and replaced `/hana` by this variable and `/hana/shared` by its corresponding variable.

I also modified `yes/no` to `true/false` in `defaults/main.yml` so we over time only use those for all roles.

2024-06-07 09:35 UTC, rhmk commented on roles/sap_hana_install/defaults/main.yml
Line 28 should be 'true' instead of false -- but it is just a comment

2024-06-07 09:41 UTC, rhmk requested changes
please correct the comments, they are misleading. The rest looks fine for me

2024-06-07 14:46 UTC, berndfinger commented
> please correct the comments, they are misleading. The rest looks fine for me
Thanks for your review! All good now (I hope).

2024-06-13 11:23 UTC, rhmk approved these changes
LGTM

2024-06-14 14:28 UTC, sean-freeman approved these changes
lgtm with backwards compatibility for the var names of directory paths (i.e. /hana)

2024-06-14 14:47 UTC, merged